### ISSUE TITLE
oldBadImageView.removeFromSuperview is not a function. (In 'oldBadImageView.removeFromSuperview()', 'oldBadImageView.removeFromSuperview' is undefined)

### ISSUE THREAD

**Issue by Eonfuzz** [nstudio/nativescript-floatingactionbutton#103]
Hey All,

Trying to get this library working with the latest nativescript 6.x.x versions and I'm getting this error occasionally when navigating to / from the page, which also crashes the app. Got any advice?

```
CONSOLE LOG file:///app/bundle.js:13295:20:  ||||| NativeScriptError in iOS ||||| TypeError: oldBadImageView.removeFromSuperview is not a function. (In 'oldBadImageView.removeFromSuperview()', 'oldBadImageView.removeFromSuperview' is undefined)
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10421a24e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x104256878 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x104bfd3d6 ffi_closure_unix64_inner
4   0x104bfddfa ffi_closure_unix64
5   0x108da0bd4 -[UIViewController __viewWillAppear:]
6   0x108ce4b60 -[UINavigationController _startCustomTransition:]
7   0x108cfb3f0 -[UINavigationController _startDeferredTransitionIfNeeded:]
8   0x108cfc7e0 -[UINavigationController __viewWillLayoutSubviews]
9   0x108cdc600 -[UILayoutContainerView layoutSubviews]
10  0x1098a3795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
11  0x10ae2bb19 -[CALayer layoutSublayers]
12  0x10ae309d3 CA::Layer::layout_if_needed(CA::Transaction*)
13  0x10ada97ca CA::Context::commit_transaction(CA::Transaction*)
14  0x10ade097e CA::Transaction::commit()
15  0x10ade16fa CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
16  0x107e77c27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
17  0x107e720be __CFRunLoopDoObservers
18  0x107e72751 __CFRunLoopRun
19  0x107e71e11 CFRunLoopRunSpecific
20  0x10efb41dd GSEventRunModal
21  0x1093b981d UIApplicationMain
22  0x104bfdc3d ffi_call_unix64
23  0x12a08ff00
JavaScript stack trace:
setImage(file:///node_modules/@nstudio/nativescript-floatingactionbutton/fab.js:19:0)
at file:///node_modules/@nstudio/nativescript-floatingactionbutton/fab.js:31:0
at applyAllNativeSetters(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:1046:0)
at initNativeView(file:///node_modules/tns-core-modules/ui/core/properties/properties.js:990:0)
at onResumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:628:0)
at _resumeNativeUpdates(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:273:0)
at onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:232:0)
at onLoaded(file:///node_modules/@nstudio/nativescript-floatingactionbutton/fab-common.js:15:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75
at callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
at callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
at loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0
at eachChildView(file:///node_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:0)
at eachChild(file:///node_modules/tns-core-modules/ui/core/view/view-common.js:1010:0)
at onLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:233:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:75
at callFunctionWithSuper(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:305:0)
at callLoaded(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:312:0)
at loadView(file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:440:0)
at file:///node_modules/tns-core-modules/ui/core/view-base/view-base.js:234:0
at eachChildView(file:///app/vendor.js:159587:<…>
```

**Comment by wuilmerj24** [comment]
Ping
