### ISSUE TITLE
Error when adding the plugin

### ISSUE THREAD

**Issue by darkshadowgks** [nstudio/nativescript-floatingactionbutton#106]
Hi, i created a new blank nativescript project and added in the plugin by using the "tns plugin add @nstudio/nativescript-floatingactionbutton"

Then, i added the import into home.component.ts
"import { registerElement } from 'nativescript-angular/element-registry';
registerElement(
  'Fab',
  () => require('@nstudio/nativescript-floatingactionbutton').Fab
);"
After that, i added button into the home.component.tns.html
<StackLayout>
    <FAB (tap)="fabTap()" icon="'~/images/ic_add_white.png'" rippleColor="#f1f1f1" class="fab-button"></FAB>
</StackLayout>

Finally i run the project by using tns run android.

However, i received the error as below and i got no clue what is it. Please help

System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
System.err:
System.err: StackTrace:
System.err: push.../node_modules/@nstudio/nativescript-floatingactionbutton/fab.js.Fab.<computed>(file:///node_modules\@nstudio\nativescript-floatingactionbutton\fab.js:82:0)
System.err:     at applyAllNativeSetters(file:///node_modules\@nativescript\core\ui\core\properties\properties.js:1046:0)
System.err:     at initNativeView(file:///node_modules\@nativescript\core\ui\core\properties\properties.js:990:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onResumeNativeUpdates(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:628:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._resumeNativeUpdates(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:273:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:232:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules\@nativescript\core\ui\core\view\view.js:247:0)
System.err:     at push.../node_modules/@nstudio/nativescript-floatingactionbutton/fab-common.js.FloatingActionButtonBase.onLoaded(file:///node_modules\@nstudio\nativescript-floatingactionbutton\fab-common.js:15:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:440:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules\@nativescript\core\ui\core\view\view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules\@nativescript\core\ui\core\view\view.js:247:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:440:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView(file:///node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules\@nativescript\core\ui\core\view\view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules\@nativescript\core\ui\core\view\view.js:247:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:440:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:234:0)
System.err:     at push.../node_modules/@nativescript/core/ui/content-view/content-view.js.ContentView.eachChildView(file:///node_modules\@nativescript\core\ui\content-view\content-view.js:70:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page-common.js.PageBase.eachChildView(file:///node_modules\@nativescript\core\ui\page\page-common.js:126:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild(file:///node_modules\@nativescript\core\ui\core\view\view-common.js:1010:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.onLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:233:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view/view.js.View.onLoaded(file:///node_modules\@nativescript\core\ui\core\view\view.js:247:0)
System.err:     at push.../node_modules/@nativescript/core/ui/page/page.js.Page.onLoaded(file:///node_modules\@nativescript\core\ui\page\page.js:43:0)
System.err:     at (file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:75)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callFunctionWithSuper(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:305:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.callLoaded(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:312:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.loadView(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:440:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addViewCore(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:435:0)
System.err:     at push.../node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._addView(file:///node_modules\@nativescript\core\ui\core\view-base\view-base.js:421:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView(file:///node_modules\@nativescript\core\ui\frame\frame.js:689:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/fragment.js.FragmentClass.onCreateView(file:///node_modules\@nativescript\core\ui\frame\fragment.js:29:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0System.err:     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
System.err:     at android.content.res.Resources.getDrawable(Resources.java:770)
System.err:     at android.content.res.Resources.getDrawable(Resources.java:742)
System.err:     ... 24 more

**Comment by bradmartin** [comment]
Gonna guess your image isn't actually in the project. Likely need to rebuild the project clean. Similar to development with native projects, you need to rebuild to ensure resources are built into the executable.
